version = 0.1
[default.deploy.parameters]
stack_name = "poc-chatbot-kendra"
resolve_s3 = true
s3_prefix = "poc-chatbot-kendra"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
